### ISSUE TITLE
Many issues...

### ISSUE THREAD

**Issue by Acecool** [HotKeyIt/ahkdll#10]
#SingleInstance On isn't recognized; On has to be removed.
#NoENV isn't recognized; has to be commented out.
AutoTrim, Off isn't recognized; has to be commented out.

IfExist <filename> isn't recognized as a valid function name; need alternative...

I'm trying to use one interface for vJoy with my framework but don't want to recode the entire thing to get it to "work".. Why is all of this, and more, missing?

**Comment by HotKeyIt** [comment]
This is because you downloaded ahk v2, see here: https://autohotkey.com/v2/v2-changes.htm
I assume you wanted the v1: https://github.com/HotKeyIt/ahkdll
Executables here: https://github.com/HotKeyIt/ahkdll-v1-release
