### ISSUE TITLE
cmd line param bug

### ISSUE THREAD

**Issue by mmikeww** [HotKeyIt/ahkdll#14]
this seems to only happen with compiled scripts

compile this script with AHK_H v1

```autohotkey
#persistent
msgbox, command line params: %0% `n %1%
return

f9::reload
```

press f9 twice, every press after the 2nd time, you get the script path itself passed as a command line parameter.

this bug existed in 1.1.24 but i just tested with 1.1.28 and still fails

**Comment by HotKeyIt** [comment]
Fixed.
