### ISSUE TITLE
Compiled exe with MultiThreadedDLL set to MultiThreaded not working anymore

### ISSUE THREAD

**Issue by TaurusPrime** [HotKeyIt/ahkdll#18]
Maybe there is a bug, but i am not able to use the compiled exe.

For testing (ahk code):
1)
FileRead, tmp, % "AutoHotkey.vcxproj"
tmp := StrReplace(tmp, "MultiThreadedDLL", "MultiThreaded")
file := FileOpen("AutoHotkey.vcxproj", "w")
file.Write(tmp)
file.Close()

FileRead, tmp, % "source\lib_pcre\lib_pcre.vcxproj"
tmp := StrReplace(tmp, "MultiThreadedDLL", "MultiThreaded")
file := FileOpen("source\lib_pcre\lib_pcre.vcxproj", "w")
file.Write(tmp)
file.Close()

and compile

2) Use new Ahk2Exe.exe compiler to create a simple msgbox.exe and run it.

If i compile it with dll, there is no problem. But not every computer has these dlls. By the way, which dlls are needed on a system to get it running?

**Comment by TaurusPrime** [comment]
Problem still exist. I tried with new update 1.30, but no change. Change from /MD to /MT results in a none working exe.

Any idea? It was working till V1.1.24. I need it for creating installers on systems, where msvcr100.dll doesn't exist.

**Comment by HotKeyIt** [comment]
Just tried it and it compiles fine, you also change this for lib_pcre!!!
