### ISSUE TITLE
Possible to get array values/object properties for v2?

### ISSUE THREAD

**Issue by prurph** [HotKeyIt/ahkdll#19]
Is there any way to get values for array/object types using the v2 dll? I'd like to do something like:

```
ahkExec("notepads := WinGetList("Notepad")
ahkgetvar("notepads[1]") // or "notepads.1", or ideally the entire array somehow
```

but I get an illegal variable name by referencing any of the properties, and I couldn't figure out if there's any way to use the result of just getting the object with `ahkgetvar("notepads")` or anything like this. I'm trying to avoid setting each property to a separate ahk variable and then `ahkgetvar`ing those.

With v1 you can do:

```
ahkExec("WinGet notepads, List, Notepad")
ahkgetvar("notepads") // => '2' (array length)
ahkgetvar("notepads1") // => "0x290530" (first id)
```

Thanks!

**Comment by HotKeyIt** [comment]
```
ahk:=AhkThread("#Persistent")
ahk.ahkExec("notepads := WinGetList(`"ahk_class Notepad`")")
Alias(notepads,ahk.ahkgetvar("notepads",1))
MsgBox notepads.1
```
If you want it to be multi-thread safe you will need to use CriticalObject:
```
ahk:=AhkThread("#Persistent")
ahk.ahkExec("notepads := CriticalObject(WinGetList(`"ahk_class Notepad`"))")
Alias(notepads,ahk.ahkgetvar("notepads",1))
MsgBox notepads.1
```
