### ISSUE TITLE
ahk.ahkgetvar always returns a pointer?

### ISSUE THREAD

**Issue by kitsu** [HotKeyIt/ahkdll#2]
From Python I try:

``` python
>>> import ctypes
>>> ahk = ctypes.cdll.AutoHotKey
>>> ahk.ahktextdll("","","")
816
>>> ahk.ahkassign("test","5")
0
>>> ahk.ahkgetvar("test",0) # As value
39321392
>>> ahk.ahkgetvar("test",1) # As pointer
39321392 # Same value either way
>>> ctypes.cast(int(ahk.ahkgetvar("test", 0)), ctypes.POINTER(ctypes.c_char))
<ctypes.LP_c_char object at 0x01EC7B20>
>>> ans = _ # Result of last operation is stored in a variable named "_"
>>> ans[0]
'5'
```

I expect ahkgetvar to return the value not a pointer, am I wrong?
Using Version 1.1.8.1 AutoHotkey_H ANSI 32-bit (on winXP64, Python2.7 32bit).

Thanks a ton for building this though, it's very helpful!

**Comment by basiltt** [comment]
Hello HotKeyIt,
Seems like 
print str(cast(ahk.ahkgetvar("test", 0), c_char_p).value) 
throwing an error. Can you share me the working code for new version.
Python version 3.7
AutoHotkey.dll version 1.1.09.01

**Comment by HotKeyIt** [comment]
Are you using ANSI? Otherwise you will need c_wchar_p.
Also what error do you get?
