### ISSUE TITLE
Change Release|Win32 back to /md

### ISSUE THREAD

**Issue by Leemonn** [HotKeyIt/ahkdll#23]
As of last [commit](https://github.com/HotKeyIt/ahkdll/commit/e9f5c1927864a97b05a3b0aa4f57715700bcdeb0)
[image](https://i.gyazo.com/9842c98fccfe1e4b3ee60f33ce1121ca.png)
there is a problem when compiling Release | Win32 because of /mt, you have to manually add "msvcrt.lib;" to Properties -> Linker -> Input -> Additional Dependencies to make it compile with no errors.
Also I don't know if this was intentional since the rest of the configurations use /md.

**Comment by HotKeyIt** [comment]
Thanks, it should be /MD. 
That has been fixed ;)
