### ISSUE TITLE
Hotstrings dont seem to work without also setting a hotkey

### ISSUE THREAD

**Issue by samcarton** [HotKeyIt/ahkdll#6]
I'm using https://github.com/amazing-andrew/AutoHotkey.Interop but I suspect the issue does not lie in that library.

The below ::wtf:: hotstring only works when the ^a hotkey has also been set. otherwise nothing seems to happen.

    //ahk.ExecRaw("^a::Send, Hello World"); // Uncomment this line to get the hotstring working
    ahk.ExecRaw("::wtf::What the Fridge?"); // This hotstring only works if a hotkey has been set

ahk.ExecRaw just calls through to the ahkdll's ahkExec function, passing along the provided string.

**Comment by HotKeyIt** [comment]
You need to #InstallKeybdHook
`ahk:=AhkThread("#Persistent`n#InstallKeybdHook")
ahk.addScript("::ahk::AutoHotkey",1)
Gui,Add,Edit,w600 r20
Gui,Show
return
GuiClose:
ExitApp`

**Comment by samcarton** [comment]
Thanks for the quick response - that did fix my problem. It's odd that AHK doesn't register the keyboard hook automatically unless a hotkey has been set. Anyway, thanks again :+1:
